{{- if .Values.monitoring.enabled }}
# ServiceMonitor for Prometheus monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arbitragex-supreme.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "arbitragex-supreme.labels" . | nindent 4 }}
    component: monitoring
spec:
  selector:
    matchLabels:
      {{- include "arbitragex-supreme.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "arbitragex-supreme.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "arbitragex-supreme.labels" . | nindent 4 }}
    component: monitoring
spec:
  groups:
  - name: arbitragex-supreme
    rules:
    - alert: ArbitrageXSupremeDown
      expr: up{job="{{ include "arbitragex-supreme.fullname" . }}"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "ArbitrageX Supreme is down"
        description: "ArbitrageX Supreme has been down for more than 1 minute."

    - alert: ArbitrageXSupremeHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"{{ include "arbitragex-supreme.fullname" . }}-.*"} / container_spec_memory_limit_bytes > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Memory usage is above 80% for ArbitrageX Supreme pod."

    - alert: ArbitrageXSupremeHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"{{ include "arbitragex-supreme.fullname" . }}-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is above 80% for ArbitrageX Supreme pod."
{{- end }}