name = "arbitragex-supreme"
main = "workers/api-proxy/pairs.ts"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "D1"
database_name = "arbitragex_cache"
database_id = "your-d1-database-id"

[env.production]
BACKEND_URL = "https://your-contabo-api.com"
