# ArbitrageX Supreme V3.0 - Cloudflare Workers Configuration
name = "arbitragex-supreme-edge"
main = "workers/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"

[env.development.vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"

# KV Namespaces for caching and storage
[[kv_namespaces]]
binding = "OPPORTUNITIES_CACHE"
id = "arbitragex_opportunities_cache"
preview_id = "arbitragex_opportunities_cache_preview"

[[kv_namespaces]]
binding = "EXECUTIONS_CACHE"
id = "arbitragex_executions_cache"
preview_id = "arbitragex_executions_cache_preview"

[[kv_namespaces]]
binding = "STRATEGIES_CACHE"
id = "arbitragex_strategies_cache"
preview_id = "arbitragex_strategies_cache_preview"

[[kv_namespaces]]
binding = "ANALYTICS_CACHE"
id = "arbitragex_analytics_cache"
preview_id = "arbitragex_analytics_cache_preview"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "arbitragex_rate_limits"
preview_id = "arbitragex_rate_limits_preview"

[[kv_namespaces]]
binding = "API_KEYS_KV"
id = "arbitragex_api_keys"
preview_id = "arbitragex_api_keys_preview"

[[kv_namespaces]]
binding = "WEBSOCKET_KV"
id = "arbitragex_websockets"
preview_id = "arbitragex_websockets_preview"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "arbitragex_analytics"
preview_id = "arbitragex_analytics_preview"

[[kv_namespaces]]
binding = "ERROR_LOGS_KV"
id = "arbitragex_error_logs"
preview_id = "arbitragex_error_logs_preview"

[[kv_namespaces]]
binding = "METRICS_KV"
id = "arbitragex_metrics"
preview_id = "arbitragex_metrics_preview"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = ""
preview_id = ""

# D1 Database bindings for edge data storage
[[d1_databases]]
binding = "OPPORTUNITIES_DB"
database_name = "opportunities-db"
preview_database_id = ""
database_id = ""

[[d1_databases]]
binding = "ARBITRAGEX_DB"
database_name = "arbitragex-edge-db"
database_id = "arbitragex-edge-db-id"

# R2 Bucket bindings for reports storage
[[r2_buckets]]
binding = "REPORTS_BUCKET"
bucket_name = "reports-bucket"

# Routes configuration
[routes]
pattern = "api.arbitragex.com/*"
zone_name = "arbitragex.com"

[routes]
pattern = "edge.arbitragex.com/*"
zone_name = "arbitragex.com"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "workers"

# Miniflare configuration for local development
[miniflare]
kv_persist = true
d1_persist = true
cache_persist = true

# Triggers for scheduled tasks
[[triggers.crons]]
cron = "*/5 * * * *"  # Every 5 minutes
name = "cache-cleanup"

[[triggers.crons]]
cron = "0 * * * *"    # Every hour
name = "metrics-aggregation"

[[triggers.crons]]
cron = "0 0 * * *"    # Daily at midnight
name = "analytics-report"

# Limits and quotas
[limits]
cpu_ms = 50000
memory_mb = 128

# Custom domains
[[custom_domains]]
pattern = "api.arbitragex.com"
certificate_id = "arbitragex-api-cert"

[[custom_domains]]
pattern = "edge.arbitragex.com"
certificate_id = "arbitragex-edge-cert"

# Analytics and monitoring
[analytics_engine_datasets]
binding = "ARBITRAGEX_ANALYTICS"

# Durable Objects for stateful operations
[[durable_objects.bindings]]
name = "WEBSOCKET_MANAGER"
class_name = "WebSocketManager"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketManager", "RateLimiter"]

# Environment-specific secrets (set via wrangler secret put)
# BACKEND_API_URL - Backend API endpoint
# BACKEND_API_KEY - Backend API authentication key
# JWT_SECRET - JWT signing secret
# ADMIN_API_KEY - Admin API key for management operations
# COINGECKO_API_KEY - CoinGecko Pro API key
# DEFILLAMA_API_KEY - DeFiLlama API key (if required)

# Compatibility settings
[compatibility_flags]
nodejs_compat = true
streams_enable_constructors = true
transformstream_enable_standard_constructor = true

# Worker placement
placement = { mode = "smart" }

# Observability
[observability]
enabled = true

# Upload rules
[rules]
"*.ts" = "Text"
"*.js" = "Text"
"*.json" = "Text"
"*.md" = "Text"
