# ArbitrageX Supreme V3.0 - Engine Worker Configuration
# Ingenio Pichichi S.A.

name = "arbitragex-engine-worker"
main = "workers/engine-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces
[[kv_namespaces]]
binding = "ARBITRAGEX_CACHE"
preview_id = "22e9b9d88bee4c308dc9fdf7e6f57ddf"
id = "94be3abe74eb4471884c312b5969c74a"

# D1 Database
[[d1_databases]]
binding = "ARBITRAGEX_DB"
database_name = "arbitragex-production"
database_id = "6ccbdfbf-4d1f-4fdd-bab5-2f2ba06b099c"

# Environment Variables
[vars]
ENVIRONMENT = "production"
ENGINE_VERSION = "3.0.0"
MAX_STRATEGIES = "13"
OPTIMIZATION_ENABLED = "true"